In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

np.array([[1,2,3],
         [4,5,6]])


array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.zeros((2,3))
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[5:8]
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr2d=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2d[2]

array([7, 8, 9])

In [53]:
arr = np.array([0,np.pi/4,np.pi/2])
np.sin(np.arange(0,np.pi,np.pi/4))


array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

: 

In [1]:
a=complex(1,2)
np.sin(3.14)

NameError: name 'np' is not defined

In [7]:
!pip install pyqt5-tools -i https://pypi.tuna.tsinghua.edu.cn/simple

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ---------------------------------------- 0.0/6.8 MB ? eta -:--:--
     -- ------------------------------------- 0.4/6.8 MB 12.2 MB/s eta 0:00:01
     ----- ---------------------------------- 0.9/6.8 MB 11.2 MB/s eta 0:00:01
     ------ --------------------------------- 1.1/6.8 MB 11.3 MB/s eta 0:00:01
     -------- ------------------------------- 1.5/6.8 MB 9.6 MB/s eta 0:00:01
     ----------- ---------------------------- 2.0/6.8 MB 9.2 MB/s eta 0:00:01
     --------------- ------------------------ 2.6/6.8 MB 9.7 MB/s eta 0:00:01
     ------------------ --------------------- 3.2/6.8 MB 10.7 MB/s eta 0:00:01
     -------------------- ------------------- 3.5/6.8 MB 10.6 MB/s eta 0:00:01
     ----------------------- ---------------- 4.1/6.8 MB 10.3 MB/s eta 0:00:01
     ------------------------ --------------- 4.2/6.8 MB 10.2 MB/s eta 0:00:01
     --------------------------- ------------ 4.7/6.8 MB 9.7 MB/s eta 0:00:01
   