In [ ]:
import torch
X = torch.arange(12,dtype = torch.float32).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],
                 [1,2,3,4],
                 [4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [7]:
Z = torch.zeros_like(Y)
print('id(Z): ',id(Z))
Z[:] = X+ Y 
print('id(Z): ',id(Z))

id(Z):  1976548324784
id(Z):  1976548324784


In [ ]:
import torch

# 1. 创建一个形状为(4,5)的二维张量
a = torch.arange(20).reshape(4, 5)
print("Step 1: a =\n", a)

# 2. 提取a的第2行(索引为1)
row_2 = a[1]
print("Step 2: 第2行 (索引为1) =\n", row_2)

# 3. 提取a的第1到第3行、第2到第4列的子张量
sub_tensor = a[0:3, 1:4]
print("Step 3: 第1到第3行，第2到第4列 =\n", sub_tensor)

# 4. 将a中所有大于10的元素替换为 -1
a[a > 10] = -1
print("Step 4: 将大于10的元素替换为 -1 =\n", a)

# 5. 将a的形状转换为 (2,2,5)
a_reshaped = a.reshape(2, 2, 5)
print("Step 5: 形状转换为 (2,2,5) =\n", a_reshaped)


Step 1: a =
 tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
Step 2: 第2行 (索引为1) =
 tensor([5, 6, 7, 8, 9])
Step 3: 第1到第3行，第2到第4列 =
 tensor([[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13]])
Step 4: 将大于10的元素替换为 -1 =
 tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1]])
Step 5: 形状转换为 (2,2,5) =
 tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, -1, -1, -1, -1],
         [-1, -1, -1, -1, -1]]])


In [3]:
import torch

# 1. 创建张量 a 和 b
a = torch.tensor([[1], [2], [3]])  # 注意 a 是列向量
b = torch.tensor([10, 20, 30])    # b 是行向量

# 2. 利用广播机制计算 a + b
result = a + b
print("Step 2: a + b =\n", result)

# 3. 提取结果张量中的第 1 行和第 3 列元素
row_1 = result[0]  # 第 1 行
col_3 = result[:, 2]  # 第 3 列
print("Step 3: 第 1 行 =\n", row_1)
print("Step 3: 第 3 列 =\n", col_3)

# 4. 将结果张量转为一维
result_flattened = result.reshape(-1)
print("Step 4: 转为一维 =\n", result_flattened)

# 5. 将结果逆序排列
result_reversed = result_flattened.flip(dims=[0])
print("Step 5: 逆序排列 =\n", result_reversed)

Step 2: a + b =
 tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])
Step 3: 第 1 行 =
 tensor([11, 21, 31])
Step 3: 第 3 列 =
 tensor([31, 32, 33])
Step 4: 转为一维 =
 tensor([11, 21, 31, 12, 22, 32, 13, 23, 33])
Step 5: 逆序排列 =
 tensor([33, 23, 13, 32, 22, 12, 31, 21, 11])


In [ ]:
import torch
u = torch.tensor([-3.0,4.0])
torch.norm(u,p=1)

tensor(7.)